.PHONY : all clean

all:
	$(MAKE) -C tinyPTC.ua
	$(MAKE) -C picoPNG.ua
	
clean:
	$(MAKE) -C tinyPTC.ua clean
	$(MAKE) -C picoPNG.ua clean

cleanall:
	$(MAKE) -C tinyPTC.ua cleanall
	$(MAKE) -C picoPNG.ua cleanall